// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.1
// source: chatsystem.proto

package chatsystem

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rcv string `protobuf:"bytes,1,opt,name=rcv,proto3" json:"rcv,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatsystem_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatsystem_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_chatsystem_proto_rawDescGZIP(), []int{0}
}

func (x *SendRequest) GetRcv() string {
	if x != nil {
		return x.Rcv
	}
	return ""
}

func (x *SendRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SendReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SendReply) Reset() {
	*x = SendReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatsystem_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReply) ProtoMessage() {}

func (x *SendReply) ProtoReflect() protoreflect.Message {
	mi := &file_chatsystem_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReply.ProtoReflect.Descriptor instead.
func (*SendReply) Descriptor() ([]byte, []int) {
	return file_chatsystem_proto_rawDescGZIP(), []int{1}
}

func (x *SendReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RecvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rcv string `protobuf:"bytes,1,opt,name=rcv,proto3" json:"rcv,omitempty"`
}

func (x *RecvRequest) Reset() {
	*x = RecvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatsystem_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvRequest) ProtoMessage() {}

func (x *RecvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatsystem_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvRequest.ProtoReflect.Descriptor instead.
func (*RecvRequest) Descriptor() ([]byte, []int) {
	return file_chatsystem_proto_rawDescGZIP(), []int{2}
}

func (x *RecvRequest) GetRcv() string {
	if x != nil {
		return x.Rcv
	}
	return ""
}

type RecvReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RecvReply) Reset() {
	*x = RecvReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatsystem_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecvReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvReply) ProtoMessage() {}

func (x *RecvReply) ProtoReflect() protoreflect.Message {
	mi := &file_chatsystem_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvReply.ProtoReflect.Descriptor instead.
func (*RecvReply) Descriptor() ([]byte, []int) {
	return file_chatsystem_proto_rawDescGZIP(), []int{3}
}

func (x *RecvReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_chatsystem_proto protoreflect.FileDescriptor

var file_chatsystem_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x68, 0x61, 0x74, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x63, 0x68, 0x61, 0x74, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x22, 0x31,
	0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x63, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x63, 0x76, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x22, 0x1d, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x22, 0x1f, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x63, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x63,
	0x76, 0x22, 0x1d, 0x0a, 0x09, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0x8d, 0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0b,
	0x53, 0x65, 0x6e, 0x64, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x63, 0x68,
	0x61, 0x74, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x0b, 0x52, 0x65, 0x63, 0x76, 0x4d, 0x61, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x63, 0x68, 0x61, 0x74, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatsystem_proto_rawDescOnce sync.Once
	file_chatsystem_proto_rawDescData = file_chatsystem_proto_rawDesc
)

func file_chatsystem_proto_rawDescGZIP() []byte {
	file_chatsystem_proto_rawDescOnce.Do(func() {
		file_chatsystem_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatsystem_proto_rawDescData)
	})
	return file_chatsystem_proto_rawDescData
}

var file_chatsystem_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chatsystem_proto_goTypes = []interface{}{
	(*SendRequest)(nil), // 0: chatsystem.SendRequest
	(*SendReply)(nil),   // 1: chatsystem.SendReply
	(*RecvRequest)(nil), // 2: chatsystem.RecvRequest
	(*RecvReply)(nil),   // 3: chatsystem.RecvReply
}
var file_chatsystem_proto_depIdxs = []int32{
	0, // 0: chatsystem.Greeter.SendMassage:input_type -> chatsystem.SendRequest
	2, // 1: chatsystem.Greeter.RecvMassage:input_type -> chatsystem.RecvRequest
	1, // 2: chatsystem.Greeter.SendMassage:output_type -> chatsystem.SendReply
	3, // 3: chatsystem.Greeter.RecvMassage:output_type -> chatsystem.RecvReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chatsystem_proto_init() }
func file_chatsystem_proto_init() {
	if File_chatsystem_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatsystem_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatsystem_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatsystem_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatsystem_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecvReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatsystem_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatsystem_proto_goTypes,
		DependencyIndexes: file_chatsystem_proto_depIdxs,
		MessageInfos:      file_chatsystem_proto_msgTypes,
	}.Build()
	File_chatsystem_proto = out.File
	file_chatsystem_proto_rawDesc = nil
	file_chatsystem_proto_goTypes = nil
	file_chatsystem_proto_depIdxs = nil
}
